variables:
  GIT_STRATEGY: clone
  
stages:
  - gradle
  - android
  - build
  - test

include:
  - local:
      '/build/gradle/.gitlab-ci.yml'
#     '/build/apk/.gitlab-ci.yml'
     
test:
  stage: test
  script:
    - echo "Testing"
    - test -f "build/info.txt"
