variables:
  GIT_STRATEGY: clone
  
stages:
  - android
  - build
  - test

include:
  - local:
#    - '/build/apk/.gitlab-ci.yml'
    - '/build/android/.gitlab-ci.yml'
test:
  stage: test
  script:
    - echo "Testing"
    - test -f "build/info.txt"
